openapi: 3.0.0
info:
  title: Crypto Observer
  version: 1.0.0
paths:
  /currency/add:
    post:
      summary: Add a cryptocurrency to the watch list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddCurrencyRequest'
      responses:
        '200':
          description: Cryptocurrency added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddCurrencyResponse'
              
  /currency/remove:
    delete:
      summary: Remove a cryptocurrency from the watch list
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Cryptocurrency removed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemoveCurrencyResponse'
                
  /currency/price:
    get:
      summary: Get the price of a cryptocurrency at a specific timestamp
      parameters:
        - name: coin
          in: query
          required: true
          schema:
            type: string
        - name: timestamp
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Price retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'

components:
  schemas:
    AddCurrencyRequest:
      type: object
      properties:
        coin:
          type: string
          description: The cryptocurrency name (e.g., BTC, ETH)
        interval:
          type: integer
          description: The interval (in seconds) for periodic price collection
      required:
        - coin
        - interval

    RemoveCurrencyRequest:
      type: object
      properties:
        coin:
          type: string
          description: The cryptocurrency name to remove from the watch list
      required:
        - coin

    AddCurrencyResponse:
      type: object
      properties:
        message:
          type: string
          example: "Cryptocurrency added successfully"
        coin:
          type: string
          description: The cryptocurrency name added
        interval:
          type: integer
          description: The interval at which the cryptocurrency price will be fetched
          
    RemoveCurrencyResponse:
      type: object
      properties:
        message:
          type: string
          example: "Cryptocurrency removed successfully"

    PriceResponse:
      type: object
      properties:
        coin:
          type: string
          description: The cryptocurrency name
        price:
          type: number
          format: float
          description: The price of the cryptocurrency at the specified timestamp
        timestamp:
          type: integer
          description: The timestamp of the price data
      required:
        - coin
        - price
        - timestamp
