name: Deploy Documentation and API to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create public directory
      run: mkdir -p public

    - name: Copy documentation files to public folder
      run: |
        cp -r ./public/* ./public/ || true

    - name: Copy API folder to public
      run: |
        cp -r ./api ./public/

    - name: Set up gh-pages branch if it does not exist
      run: |
        git fetch origin gh-pages || git checkout --orphan gh-pages

    - name: Commit and Push changes to gh-pages
      run: |
        git add .
        git commit -m "Deploy Documentation and API" || echo "No changes to commit"
        git push origin gh-pages --force

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: public
        token: ${{ secrets.GITHUB_TOKEN }}
