name: Deploy Documentation and API to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy documentation files to public folder
      run: |
        cp -r ./api/ ./public/ || true

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: main
        folder: public
        token: ${{ secrets.GITHUB_TOKEN }}
